"""add_impact_size_field_to_tasks

Revision ID: 42fc581cb5d1
Revises: c725adf3b3e7
Create Date: 2025-06-14 19:28:46.080988+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42fc581cb5d1'
down_revision: Union[str, None] = 'c725adf3b3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('impact_size', sa.Enum('ROCK', 'PEBBLES', 'SAND', name='adhdimpactsize'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'impact_size')
    # ### end Alembic commands ###
