"""Fix foreign key relationships for User tasks

Revision ID: c725adf3b3e7
Revises: 7c0d6933714d
Create Date: 2025-06-14 12:28:23.622664+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c725adf3b3e7'
down_revision: Union[str, None] = '7c0d6933714d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
