"""Add group invitations table

Revision ID: 189ecaaec8f3
Revises: 42fc581cb5d1
Create Date: 2025-06-17 18:35:07.771947+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '189ecaaec8f3'
down_revision: Union[str, None] = '42fc581cb5d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('invited_email', sa.String(length=100), nullable=False),
    sa.Column('invited_user_id', sa.Integer(), nullable=True),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='invitationstatus'), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adhd_welcome_settings', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_invitations_id'), 'group_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_group_invitations_invited_email'), 'group_invitations', ['invited_email'], unique=False)
    op.create_index(op.f('ix_group_invitations_token'), 'group_invitations', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_invitations_token'), table_name='group_invitations')
    op.drop_index(op.f('ix_group_invitations_invited_email'), table_name='group_invitations')
    op.drop_index(op.f('ix_group_invitations_id'), table_name='group_invitations')
    op.drop_table('group_invitations')
    # ### end Alembic commands ###
